version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - obdata_dev:/var/lib/openbazaar
      - .:/go/src/github.com/developertask/openbazaar-go
    ports:
      - "4001:4001"
      - "4002:4002"
      - "9005:9005"
    security_opt:
      - seccomp:unconfined #req: delve for golang
  server:
    image: openbazaar/server
    ports:
      - 4001
      - 4002
      - 9005
    volumes:
      - obdata:/var/lib/openbazaar

volumes:
  obdata:
  obdata_dev:
